### ISSUE TITLE
ESP32s3 - Timeout while connecting to panel with ESPHome

### ISSUE THREAD

**Issue by domasist** [cybertza/PAI-ESP32#4]
I flashed ESP32s3 with ESPHome and I got **PAI.paradox.paradox - Timeout while connecting to panel**. I tried all combination with GPIOs and reversing rx and tx on the alarm board, but still the same result: **PAI - Unable to connect to alarm**.  ESPHome is working, I am able to connect to it over telnet. Only missing part is connection to the Alarm. 

**I would like to know how to test, if the serial connection to the alarm is correct and working.** 

I tested GPIOs based on ESP32s3 [pinout](https://i0.wp.com/randomnerdtutorials.com/wp-content/uploads/2024/09/ESP32-S3-pinout.jpg?quality=100&strip=all&ssl=1) 
not working: 
  tx_pin: GPIO43  # purple wire tx -> to rx on board (down)
  rx_pin: GPIO44  # yellow wire rx -> to tx on board (up)
not working: 
  tx_pin: GPIO17  # purple wire tx -> to rx on board (down)
  rx_pin: GPIO18  # yellow wire rx -> to tx on board (up)

**Connection to the board:**

![Image](https://github.com/user-attachments/assets/2dd7b601-6c55-44f8-ae02-cb77cc336f86)

**My yaml**
```
esphome:
  name: "a-paradox-alarm"
  friendly_name: "a-paradox-alarm"
  min_version: 2024.11.0
  name_add_mac_suffix: false

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

# Enable logging
logger:

wifi:
  networks:
  -  ssid: !secret wifi_ssid_xxxxxxx1
     password: !secret wifi_password_xxxxxxx1
  -  ssid: !secret wifi_ssid_xxxxxxx2
     password: !secret wifi_password_xxxxxxx2

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: $name "Hotspot"
    password: !secret wifi_ap_password

captive_portal:

# Example configuration entry
web_server:
  port: 80

# Enable Home Assistant API
api:
  encryption:
    key: "xxxxxxxxxxx"

ota:
  - platform: esphome
    password: !secret ota_password

# external component for paradox alarm
external_components:
  - source: github://oxan/esphome-stream-server

# uart component for paradox alarm
uart:
  id: uart_bus
  # add further configuration for the UART here
  baud_rate: 9600
  tx_pin: GPIO43  # purple wire tx -> to rx on board (down)
  rx_pin: GPIO44  # yellow wire rx -> to tx on board (up)
  # tx_pin: GPIO17  # purple wire tx -> to rx on board (down)
  # rx_pin: GPIO18  # yellow wire rx -> to tx on board (up)
  # tx2 and rx2 UART2 - TX: GPIO16, RX: GPIO17 (Only on ESP32)

# stream server for paradox alarm
stream_server:
  uart_id: uart_bus
  port: 23

# bubary sensor stream server paradox alarm
binary_sensor:
  - platform: stream_server
    connected:
      name: Connected

# sensor stream server for paradox alarm 
sensor:
  - platform: stream_server
    connection_count:
      name: Number of connections
```
